# Generated by Django 3.0.2 on 2020-01-31 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('previous_clearance', models.BooleanField(default=False)),
                ('previous_protocol_number', models.CharField(blank=True, max_length=255)),
                ('has_deception', models.BooleanField(default=False)),
                ('has_grant_application', models.BooleanField(default=False)),
                ('grant_agency', models.CharField(blank=True, max_length=255)),
                ('grant_release_date', models.DateField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'PI'), (2, 'RA')])),
                ('is_certified', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
