# Generated by Django 3.0.2 on 2020-02-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='instructions',
            field=models.FileField(upload_to='instructions/'),
        ),
    ]
