# Generated by Django 3.0.2 on 2020-01-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200131_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creator',
        ),
        migrations.AddField(
            model_name='projectresearcher',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
