# Generated by Django 2.2.6 on 2019-10-27 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191027_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherProjectRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'PI'), (2, 'RA')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researcher_project_relationships', to='projects.Project')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Researcher')),
            ],
        ),
        migrations.DeleteModel(
            name='ResearcherRelationship',
        ),
    ]
