# Generated by Django 3.0.2 on 2020-01-31 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20200131_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectresearcher',
            name='is_owner',
        ),
        migrations.AlterField(
            model_name='projectresearcher',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchers', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='projectresearcher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
