# Generated by Django 2.2.6 on 2019-10-28 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20191027_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherprojectrelationship',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='projects.Project'),
        ),
    ]
