# Generated by Django 2.2.6 on 2019-10-28 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20191028_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='grant_agency',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='grant_release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='has_deception',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='has_grant_application',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='previous_clearance',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='previous_protocol_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
