# Generated by Django 2.2.6 on 2019-10-30 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20191028_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'PI'), (2, 'RA')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_group', to='projects.Project')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_group', to='projects.Researcher')),
            ],
        ),
        migrations.DeleteModel(
            name='ResearcherProjectRelationship',
        ),
    ]
