# Generated by Django 2.2.6 on 2019-10-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20191030_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='grant_agency',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='grant_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='has_deception',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='has_grant_application',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='previous_clearance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='previous_protocol_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
